django/modelManager/modelManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modelApp import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showmodels/', views.showModels),
    url(r'^prediction/(?P<model_name>.+)', views.prediction),
    url(r'^graph/(?P<graph_name>.+)', views.graph),
    url(r'^addPoint/(?P<graph_name>.+)', views.addPoint),
    url(r'^getStreamingSymbole/(?P<graph_name>.+)', views.getStreamingSymbole),
    url(r'^getTrainingEntry/(?P<model_name>.+)', views.getTrainingEntry),
    url(r'^getAllCombiModelGraph/', views.getAllCombiModelGraph), # getAllCombiModelGraph
]

django/modelManager/modelApp/models.py
from django.db import models

# Create your models here.
class PredictModel(models.Model):
    name = models.CharField(max_length=200)
    isTrained = models.BooleanField()
    def __unicode__(self):
        return self.name
    
class Entry(models.Model):
    name = models.CharField(max_length=200)
    predictModel = models.ForeignKey(PredictModel)
    def __unicode__(self):
        return self.name
    
class Symbole(models.Model):
    symbole = models.CharField(max_length=200)
    entry = models.ForeignKey(Entry)
    def __unicode__(self):
        return self.symbole
    
class Keyword (models.Model):
    keyword = models.CharField(max_length=200)
    entry = models.ForeignKey(Entry)
    def __unicode__(self):
        return self.keyword
    
class PredictGraph(models.Model):
    name = models.CharField(max_length=200)
    predictModel = models.ForeignKey(PredictModel)
    symbole = models.CharField(max_length=200)
    def __unicode__(self):
        return 'graph for %s with %s' % (self.predictModel.name, self.symbole)
        
class PredictPoint(models.Model):
    # TODO check format
    newsPubDate = models.DateTimeField()
    newsSource = models.CharField(max_length=200)
    newsText = models.TextField()
    predictScore = models.FloatField()
    predictGraph = models.ForeignKey(PredictGraph)
    def __unicode__(self):
        return '[%s]news from %s : %s... with score %f' % (str(self.newsPubDate), self.newsSource, self.newsText[:50], self.predictScore)

django/modelManager/modelApp/views.py
from django.shortcuts import render
from modelApp.models import PredictModel
from modelApp.models import PredictGraph
from modelApp.models import PredictPoint
from django.http import HttpResponse
from django.utils import timezone

import pygal
from datetime import timedelta
from tools_django import matrix_normalize
from tools_django import predictPointToList
# Create your views here.
def index(request):
    return render(request, 'index.html', {})
    
def showModels(request):
    myPredictModels = PredictModel.objects.all()
    return render(request, 'showmodels.html', {'models' : myPredictModels})
        
def graph(request, graph_name):
    hours = 50
    numberOfX = 4
    
    graph = PredictGraph.objects.get(name=graph_name)
    
    #end = datetime.now()
    end = timezone.now() + timedelta(hours=2)
    start = end - timedelta(hours=hours)

    labels = []
    dx = hours/float(numberOfX-1)
    for i in range(numberOfX):
        labels.append(str(start + timedelta(hours=dx*i)))
    stackedline_chart = pygal.StackedLine(fill=True, x_label_rotation=30)
    stackedline_chart.title = 'market prediction (# of news) [' + str(graph_name) + ']'
    stackedline_chart.x_labels = labels
    veryBad = predictPointToList(graph.predictpoint_set.filter(predictScore=0.0), hours=hours, numberOfX=numberOfX)
    bad = predictPointToList(graph.predictpoint_set.filter(predictScore=1.0), hours=hours, numberOfX=numberOfX)
    good = predictPointToList(graph.predictpoint_set.filter(predictScore=2.0), hours=hours, numberOfX=numberOfX)
    veryGood = predictPointToList(graph.predictpoint_set.filter(predictScore=3.0), hours=hours, numberOfX=numberOfX)
    matrix_normalize([veryBad, bad, good, veryGood])

    stackedline_chart.add('Very bad', veryBad)
    stackedline_chart.add('Bad', bad)
    stackedline_chart.add('Good', good)
    stackedline_chart.add('Very good', veryGood)
    return HttpResponse(stackedline_chart.render()) 
    #stackedline_chart.render()
    
def getTrainingEntry(request, model_name):
    if(model_name):
        try:
            myPredictModel = PredictModel.objects.get(name=model_name)
            entry = myPredictModel.entry_set.all()
            myList = []
            for record in entry:
                subDict = {}
                subDict['symboles'] = []
                subDict['keywords'] = []
                for symbole in record.symbole_set.all():
                    subDict['symboles'].append(symbole.symbole)
                for keyword in record.keyword_set.all():
                    subDict['keywords'].append(keyword.keyword)
                myList.append(subDict)
            return HttpResponse(str(myList))
        except Exception as e:
            return HttpResponse(str(e)) # TODO improve error
    return HttpResponse('') # TODO improve error

def getStreamingSymbole(request, graph_name):
    if(graph_name):
        try:
            myGraphModel = PredictGraph.objects.get(name=graph_name)
            symbole = myGraphModel.symbole
            return HttpResponse(str(symbole))
        except Exception as e:
            return HttpResponse(str(e)) # TODO improve error
    return HttpResponse('') # TODO improve error
    
def prediction(request, model_name):
    if(model_name == None):
        return showModels(request)
    try:
        myPredictModel = PredictModel.objects.get(name=model_name)
        return render(request, 'prediction.html', {'model' : myPredictModel})
    except:
        return showModels(request) # TODO better error
    
def addPoint(request, graph_name):
    if(graph_name == None):
        return HttpResponse('')
    try:
        myPredictGraph = PredictGraph.objects.get(name=graph_name)
        point = request.POST # no security
        existePoints = PredictPoint.objects.filter(newsText=point['newsText'], predictGraph=myPredictGraph)
        if not existePoints:
            newPoint = PredictPoint(newsPubDate=point['newsPubDate'], newsSource=point['newsSource'], newsText=point['newsText'], predictScore=point['predictScore'], predictGraph=myPredictGraph)
            newPoint.save()
        return HttpResponse('OK')
    except Exception as e:
            return HttpResponse(str(e)) # TODO improve error
            
def getAllCombiModelGraph(request):
    combi = []
    predictModels = PredictModel.objects.all()
    for model in predictModels:
        for graph in PredictGraph.objects.filter(predictModel=model):
            combi.append((model.name, graph.name))
    return HttpResponse(str(combi)) 

django/modelManager/templates/base.html
<html>
    <head>
        <title>Market predictions</title>
        <link rel="stylesheet" type="text/css" media="all" href="/static/css/base.css" />
    </head>
    <body>
    <ul id="nav"><!-- 
        --><li><a href="/">index</a></li><!-- 
        --><li><a href="/showmodels">show models</a></li>
    </ul> 
    <div id="main_content">
        {% block main_content %}
        {% endblock %}
    </div>
    </body>
</html>

django/modelManager/templates/index.html
{% extends 'base.html' %}
{% block main_content %}
<h1>main page</h1>
{% endblock %}

django/modelManager/templates/prediction.html
{% extends 'base.html' %}
{% block main_content %}
<h1>show model prediction</h1>
        <p>{{ model.name }}</p>
        <ul>
        {% for entry in model.entry_set.all %}
            <li>{{ entry.name }}</li>
            <ul>
            <li> List of symboles
            {% for symbole in entry.symbole_set.all %}
                <span>{{ symbole.symbole }}</span>
            {% endfor %}
            </li>
            <li>
            List of keywords
            {% for keyword in entry.keyword_set.all %}
                <span>{{ keyword.keyword }}</span>
            {% endfor %}
            </li>            
            </ul>
        {% endfor %}
        </ul>
        <p>graphes</p>
        {% for graph in model.predictgraph_set.all %}
            {{ graph }}
            <figure>
              <embed type="image/svg+xml" src="/graph/{{ graph.name }}" width="600" height="480" />
            </figure>
            <table id="{{ graph.name }}" class="tablesorter"> 
            <thead> 
            <tr> 
                <th>Pub. date</th> 
                <th>Source</th> 
                <th>Text</th> 
                <th>Score</th> 
            </tr> 
            </thead> 
            <tbody> 
            {% for point in graph.predictpoint_set.all %}
                <tr>
                    <td>{{ point.newsPubDate }}</td>
                    <td>{{ point.newsSource }}</td>
                    <td>{{ point.newsText }}</td>
                    <td>{{ point.predictScore }}</td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endfor %}
{% endblock %}

django/modelManager/templates/showmodels.html
{% extends 'base.html' %}
{% block main_content %}
<h1>show models</h1>
    {% for model in models %}
        <p><a href="/prediction/{{ model.name }}">{{ model.name }}</a></p>
        <ul>
        {% for entry in model.entry_set.all %}
            <li>{{ entry.name }}</li>
            <ul>
            <li> List of symboles
            {% for symbole in entry.symbole_set.all %}
                <span>{{ symbole.symbole }}</span>
            {% endfor %}
            </li>
            <li>
            List of keywords
            {% for keyword in entry.keyword_set.all %}
                <span>{{ keyword.keyword }}</span>
            {% endfor %}
            </li>            
            </ul>
        {% endfor %}
        </ul>
    {% endfor %}
{% endblock %}